//GET http://localhost:3000


//POST http://localhost:3000/api/authentification/register
POST http://localhost:3000/authentification/login
Content-Type: application/json

{
    "subscriberId": "Lucie"
}

