//APP message
GET http://localhost:3000


//SUBSCRIBERS

###
//user registration
POST http://localhost:3000/api/authentification/register
Content-Type: application/json

{
    "subscriberId": "Lucion",
    "email": "coucoubjr@salut.fr",
    "password": "blip"
}
###
//user login
POST http://localhost:3000/api/authentification/login
Content-Type: application/json

{
    "subscriberId": "Lucion",
    "email": "coucoubjr@salut.fr",
    "password": "blip"
}

###
//get all users
GET http://localhost:3000/api/authentification


###
//get one user
GET http://localhost:3000/api/authentification/60e1e91cce0e913168606bf1


###
//delete user
DELETE http://localhost:3000/api/authentification/60e1b9e5817e5d2f30230532

###


//SITES 

//create site 
POST http://localhost:3000/api/sites/addSite
Content-Type: application/json

{
    "siteName": "Psiri",
    "description": "very nice neighborhood",
    "siteType": ["lieux"]
}
###

//get all sites
GET http://localhost:3000/api/sites

###
//get one site
GET http://localhost:3000/api/sites/60e2cf9fab8bac35889d3c13

###
//delete one site
DELETE http://localhost:3000/api/sites/60e33afc1c916827f068b57c

###
//get site : search by category
GET http://localhost:3000/api/sites?typeis=neighborhood

###
//get site: search by keyword
GET http://localhost:3000/api/sites?keyword=hood
