//APP message
GET http://localhost:3000


//SUBSCRIBERS

###
//user registration
POST http://localhost:3000/api/authentification/register
Content-Type: application/json

{
    "subscriberId": "alice",
    "email": "alicemainguet@hello.fr",
    "password": "blup"
}
###
//user login
POST http://localhost:3000/api/authentification/login
Content-Type: application/json

{
    "subscriberId": "alice",
    "password": "blup"
}

###
//get all users
GET http://localhost:3000/api/authentification


###
//get one user
GET http://localhost:3000/api/authentification/60e1df003de5842a54d286f1


###
//delete user
DELETE http://localhost:3000/api/authentification/60e1df003de5842a54d286f1

###


//SITES 

//create site 
POST http://localhost:3000/api/sites/addSite
Content-Type: application/json

{
    "siteName": "Psiri",
    "description": "Very nice and animated neighborhood in the center of Athens. Lot of bars and restaurants!",
    "siteType": ["neighborhood"]
}

###
//update a sites
GET http://localhost:3000/api/sites/60e569464f21ff34708cda75
{
    "siteType": ["green area"]
}
###
//get all sites
GET http://localhost:3000/api/sites

###
//get one site
GET http://localhost:3000/api/sites/60e2cf9fab8bac35889d3c13

###
//delete one site
DELETE http://localhost:3000/api/sites/60e563984f21ff34708cda62



###
//get all sites 
GET http://localhost:3000/api/sites


###
//get site : search by category
GET http://localhost:3000/api/sites?typeis=hill

###
//get site: search by keyword
GET http://localhost:3000/api/sites?keyword=Lycab
